replicaCount: 1

image:
  repository: todo-list-be
  tag: ""
  pullPolicy: IfNotPresent

containerPort: 9000

service:
  type: ClusterIP
  port: 9000

env:
  port: "9000"
  dbHost: "todo-db"
  dbPort: "5432"
  dbUser: "dev_user"
  dbPassword: "dev_pass"
  dbName: "dev_db"
  dbSSLMode: "disable"

existingSecret: "postgres-secret"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
