apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-list-be.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "todo-list-be.name" . }}
    helm.sh/chart: {{ include "todo-list-be.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "todo-list-be.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "todo-list-be.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          env:
            - name: PORT
              value: "{{ .Values.env.port }}"
            - name: DB_HOST
              value: "{{ .Values.env.dbHost }}"
            - name: DB_PORT
              value: "{{ .Values.env.dbPort }}"
            - name: DB_USER
              value: "{{ .Values.env.dbUser }}"
            - name: DB_PASSWORD
              value: "{{ .Values.env.dbPassword }}"
            - name: DB_NAME
              value: "{{ .Values.env.dbName }}"
            - name: DB_SSLMODE
              value: "{{ .Values.env.dbSSLMode }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
